### ISSUE TITLE
No server list

### ISSUE THREAD

**Issue by jmmendivil** [hardpixel/hotel-manager#3]
There's no server list on the menu

![screenshot from 2018-11-08 12-37-51](https://user-images.githubusercontent.com/1274534/48347833-14bf1880-e645-11e8-9fe7-f1845a780c4f.png)

even when Hotel works ok on its own

![screenshot from 2018-11-08 12-39-08](https://user-images.githubusercontent.com/1274534/48347840-18eb3600-e645-11e8-87ac-93082bb79c31.png)

I checked on http://localhost:2000/_/servers and seems like a valid JSON

_SO: Fedora 28; extension installed from Gnome Shell Extensions page_

**Comment by Nsbx** [comment]
Same error with Ubuntu 18.04.1 LTS x86_64
And when you try to open the link for Hotel the extension open a link to hotel.undefined

Edit: Solved with .hotelrc in my profile with this path "/usr/local/bin/hotel"
(hotel installed in global with yarn as root ...)
you need to reload the extension after that : https://extensions.gnome.org/extension/1137/gnome-shell-extension-reloader/

**Comment by olibia** [comment]
Hi, thanks for reporting this. There should be a config file `~/.hotel/conf.json`. Hotel manager reads this file to find the tld. 

Default config contains the following:

```json
{
  "port": 2000,
  "host": "127.0.0.1",
  "timeout": 5000,
  "tld": "localhost",
  "proxy": false
}
```
Can you confirm that your configuration has the tld set?

Also, could you try the following command and paste the output here?
`journalctl | grep hotel-manager`

**Comment by Nsbx** [comment]
Hi
i repost my edit here :

Edit: Solved with .hotelrc in my profile with this path "/usr/local/bin/hotel"
(hotel installed in global with yarn as root ...)
you need to reload the extension after that : https://extensions.gnome.org/extension/1137/gnome-shell-extension-reloader/

Thank great extension :)

**Comment by olibia** [comment]
@Nsbx great, thanks!
 
@jmmendivil could you try using the extension from the master branch? I added a fix that could solve your issue.

**Comment by jmmendivil** [comment]
@olibia I did it, but the problem persist.

I looked over the _conf.json_ file and the content it's just an empty object.

[Hotel creates the file with and empty object by default, if you have no _conf.json_](https://github.com/typicode/hotel/blob/master/src/conf.js#L20), so maybe you should validate for an empty object too.

As a workaround, I just added the same default keys to it, and now it's working.

btw. great extension!
